      real*8 piov2, pi, twopi
      real*8 c_speed, eps_0, e_mass, e_charge
      real*8 r_earth


      parameter ( piov2    = 1.5707963267948966192d0 )
      parameter ( pi       = 3.1415926535897932385d0 )
      parameter ( twopi    = 6.2831853071795864769d0 )
      
      parameter ( c_speed  = 299792458.d0 )
      parameter ( eps_0    = 8.8541878176203898505d-12 )
      parameter ( e_mass   = 9.10938356d-31 )
      parameter ( e_charge = 1.6021766208d-19 )
      
      parameter ( r_earth = 6.370d3 )

