clearvars
fclose all;


savepath = 'C:\hcburch\Research\Dissertation\Prelminary_work\inputs\';

% %full resolution
% hprime = 68:.1:87;
% beta = 0.3:0.002:0.66;

%expand exponential search space
hprime = 87.1:.1:90;
beta = 0.1:0.002:0.3-0.002;

rxdists = [532,1388,2084];
%NAA to EG
txname = 'NAA';
txdata = 'NAA240';
% rxname = 'EG';
rxnames = {'EG';'CN';'CB'};
rxlats = [41.9508333 35.966661 29.943509];
rxlons = [72.7235556 79.096591 82.029749];
% rxlat = 41.9508333;
% rxlon = 72.7235556;
% rxlat = 35.966661;
% rxlon = 79.096591;
% rxlat = 29.943509;
% rxlon = 82.029749;

for rr = 1:length(rxdists)
    rxlat = rxlats(rr);
    rxlon = rxlons(rr);
    rxname = rxnames{rr};
    rxdist = rxdists(rr);
    for n=1:length(hprime)
        for m=1:length(beta)
            basename = sprintf('%1$03.fb%2$03.f_%3$s-%4$s',...
                hprime(n)*10,beta(m)*1000,txname,rxname);
            fid = fopen([savepath rxname '\' basename '.inp'],'w');
            fprintf(fid,['case-id     run_lwpm() Python\n'...
                'tx          ' basename '\n'...
                'tx-data      ' txdata '\n'...
                sprintf('ionosphere  homogeneous exponential %f %f\n', beta(m), hprime(n))...
                sprintf('range-max   %5.0f\n',rxdist+50)...
                sprintf('receivers     %f   %f\n',rxlat,rxlon)...
                'mc-options  full-wave 0 true\n'...
                'lwflds\n'...
                'print-mds   0\n'...
                'print-wf    2\n'...
                'print-lwf   2\n'...
                'print-swg   2\n'...
                'print-mc    1\n'...
                'start\n'...
                'quit']);
            fclose(fid);
        end
    end
end

% %NAA to CN
% txname = 'NAA';
% txdata = 'NAA240';
% rxname = 'CN';
% rxlat = 35.966661;
% rxlon = 79.096591;
% for nn=1:length(logno)
%     for hh=1:length(h_0)
%         for ss=1:length(H)
%             basename_inp = sprintf('%03.fn%02.fs%02.f_%s-%s',h_0(hh),logno(nn),H(ss),txname,rxname);
%             basename_prf = sprintf('%03.fn%02.fs%02.f',h_0(hh),logno(nn),H(ss));
%             fid = fopen([savepath rxname '\' basename_inp '.inp'],'w');
%             fprintf(fid,['case-id     run_lwpm() Python\n'...
%                 'tx          ' basename_inp '\n'...
%                 'tx-data      ' txdata '\n'...
%                 sprintf('ionosphere  homogeneous table /blue/moore/hcburch/lwpv3/test/p/%s.prf\n',basename_prf)...
%                 'range-max   2200.0\n'...
%                 sprintf('receivers     %f   %f\n',rxlat,rxlon)...
%                 'mc-options  full-wave 0 true\n'...
%                 'lwflds\n'...
%                 'print-mds   0\n'...
%                 'print-wf    2\n'...
%                 'print-lwf   2\n'...
%                 'print-swg   2\n'...
%                 'print-mc    1\n'...
%                 'start\n'...
%                 'quit']);
%             fclose(fid);
%         end
%     end
% end
% 
% %NAA to CB
% txname = 'NAA';
% txdata = 'NAA240';
% rxname = 'CB';
% rxlat = 29.943509;
% rxlon = 82.029749;
% for nn=1:length(logno)
%     for hh=1:length(h_0)
%         for ss=1:length(H)
%             basename_inp = sprintf('%03.fn%02.fs%02.f_%s-%s',h_0(hh),logno(nn),H(ss),txname,rxname);
%             basename_prf = sprintf('%03.fn%02.fs%02.f',h_0(hh),logno(nn),H(ss));
%             fid = fopen([savepath rxname '\' basename_inp '.inp'],'w');
%             fprintf(fid,['case-id     run_lwpm() Python\n'...
%                 'tx          ' basename_inp '\n'...
%                 'tx-data      ' txdata '\n'...
%                 sprintf('ionosphere  homogeneous table /blue/moore/hcburch/lwpv3/test/p/%s.prf\n',basename_prf)...
%                 'range-max   2200.0\n'...
%                 sprintf('receivers     %f   %f\n',rxlat,rxlon)...
%                 'mc-options  full-wave 0 true\n'...
%                 'lwflds\n'...
%                 'print-mds   0\n'...
%                 'print-wf    2\n'...
%                 'print-lwf   2\n'...
%                 'print-swg   2\n'...
%                 'print-mc    1\n'...
%                 'start\n'...
%                 'quit']);
%             fclose(fid);
%         end
%     end
% end

% %NAA to CB
% for n=1:length(hprime)
%     for m=1:length(beta)
%         for nn=1:length(coefnu)
%             for mm=1:length(expnu)
%                 fid = fopen([savepath 'NAA\' sprintf('%1$03.fb%2$02.f-%3$04.fb%4$4.f_NAA.lwpc',...
%                     hprime(n)*10,beta(m)*100,log(coefnu(nn))*100,abs(expnu(mm)*10000))],'w');
%                 fprintf(fid,['/ufrc/moore/hcburch/LWW/LWW/gtest/\n'...
%                     '1\n'...
%                     sprintf('/ufrc/moore/hcburch/LWW/LWW/p/d/%1$03.fb%2$02.f.prof\n',hprime(n)*10,beta(m)*100)...
%                     '1\n'...
%                     sprintf('/ufrc/moore/hcburch/LWW/LWW/p/c/%1$04.fb%2$4.f.prof\n',log(coefnu(nn))*100,abs(expnu(mm)*10000))...
%                     'RUN1\n'...
%                     'RUN11\n'...
%                     ' &datum\n'...
%                     ' power=1 freq=24.000 trlat=44.63573 trlong=67.22993\n'...
%                     ' rclat=29.943 rclong=82.029\n'...
%                     ' max_alt=100\n'...
%                     ' insphtype0=(1,1)\n'... 
%                     ' &end']);
%                 fclose(fid);
%             end
%         end
%     end
% end
