function [rho, sigma, epsr, eigen, eigens, ht, Ex_mag, Ex_ang, Ey_mag, Ey_ang, Ez_mag, Ez_ang, ...
    Hx_mag, Hx_ang, Hy_mag, Hy_ang, Hz_mag, Hz_ang, fofr, T1, T2, T3, T4, Amk] ...
    = read_output_lwpv3_T_fofr(output_path, log_file)
% function [rho, sigma, epsr, eigen50, eigens50, ht, Ex_mag, Ex_ang, Ey_mag, Ey_ang, Ez_mag, Ez_ang, ...
%     Hx_mag, Hx_ang, Hy_mag, Hy_ang, Hz_mag, Hz_ang, T1, T2, T3, T4, Amk] ...
%     = read_output_lwpv3_T(output_path, log_file)
% function [rho, sigma, epsr, eigenavg, eigensavg, ht, Ex_mag, Ex_ang, Ey_mag, Ey_ang, Ez_mag, Ez_ang, ...
%     Hx_mag, Hx_ang, Hy_mag, Hy_ang, Hz_mag, Hz_ang, T1, T2, T3, T4, Amk] ...
%     = read_output_lwpv3_T(output_path, log_file)      atten, voverc

%This function reads and interprets the .log file generated by LWPC version
%3.0 with print-mds = 0, print-wf = 2, and print-lwf = 2, print-swg = 2, and print-mc =1. 
%inputs: path to the log file and log file name
%outputs: cross-referenced arrays of distances, eigen angles, heights, and 
%field components (Ex,y,z and Hx,y,z)
%rho(m): distance from transmitter as a function of slab
%eigen(m,neigen): eigen angles as a function of slab and mode in degrees
%eigen50(m,neigen): same but evaluated at h=50km
%E or H(h,m,neigen): field as a function of height, slab, and mode
%T1-4, f(R): used to calculate mode excitation parameters
%Amk: conversion coefficients Amk{s}(m1,m2) converts mode m1 to mode m2 at
%slab s

% clearvars
% fclose all
% output_path = '\\wsl.localhost\Ubuntu\home\qdh0004\git_repos\LWPC\LWPCv21\instruct\';
% log_file = '900b660h1100_NAA-AU.log';
Amk = {0};
%disp([output_path,log_file])
fid = fopen([output_path log_file]);
tline = fgetl(fid);
n = 1; %text line counter
m = 0; %slab counter
neigen = 1; %eigenangle counter
% while not(strncmp(tline,'quit',length('quit'))) %run til end of file
while ~feof(fid) %run til end of file
    tline = fgetl(fid); %read in line of text
    n = n+1;
    if strncmp(tline, 'mds    lat',length('mds    lat')) %new slab boundary
        m = m+1;
        neigen = 0;
        
        %move down one line to read in slab parameters
        tline = fgetl(fid);
        n = n+1;
        
        %read in slab parameters as floating-point numbers
        A = sscanf(tline,'%f');
        if ~contains(tline,'      99.0') %don't read in if it's the end of the path
            mds(m) =    A(1);
            lat(m) =    A(2);
            lon(m) =    A(3);
            rho(m) =    A(4);
            azim(m) =   A(5);
            dip(m) =    A(6);
            bfield(m) = A(7);
            sigma(m) =  A(8);
            epsr(m) =   A(9);
            beta(m) =   A(10);
            hpr(m) =    A(11);
            
            %move down two lines to read in eigenangles and T parameters
            tline = fgetl(fid);
            n = n+1;
            tline = fgetl(fid);
            n = n+1;
        
    
        
            for neigen = 1:mds(m) %for each mode
                A = sscanf(tline,'%f');
                eigen(m,neigen) = complex(A(2),A(3));
                eigens{m}(neigen) = eigen(m,neigen);
                T1(m,neigen) = complex(A(4),A(5));   
                T2(m,neigen) = complex(A(6),A(7)); 
                T3(m,neigen) = complex(A(8),A(9));
                T4(m,neigen) = complex(A(10),A(11)); 
                fofr(m,neigen) = complex(A(12),A(13)); 
                
                tline = fgetl(fid);%advance one line and read in the next mode
                n = n+1;
            end
        else
            m = 0; %reset the slab counter at the end of path
            neigen = 1; %reset the eigenangle counter
        end
                    
    end
    if strncmp(tline, '   rho',length('   rho'))
        m = m + 1;  %detect new slab in htgain outputs
        neigen = 1; %start over counting modes in new slab
    end
    %if strncmp(tline, '   ht', length('   ht')) %read in the table of field values vs height
    if strncmp(tline, 'WF_DRIVER: wfht1', length('WF_DRIVER: wfht1')) %read in the table of field values vs height
        tline = fgetl(fid);
        n = n+1;
        A = sscanf(tline,'WF_DRIVER: azim= %f eigen= %f %f at h=50.');
        eigen50(m,neigen) = complex(A(2),A(3)); %eigenangles at h = 50km
        eigens50{m}(neigen) = eigen50(m,neigen);
        tline = fgetl(fid);
        n = n+1;
        tline = fgetl(fid);
        n = n+1;
        for h = 1:65
            tline = fgetl(fid);
            n = n+1;
            A = sscanf(tline,'%f');
            ht(h,m) =     A( 1);
            Ex_mag(h,m,neigen) = A( 2);
            Ex_ang(h,m,neigen) = A( 3);
            Ey_mag(h,m,neigen) = A( 4);
            Ey_ang(h,m,neigen) = A( 5);
            Ez_mag(h,m,neigen) = A( 6);
            Ez_ang(h,m,neigen) = A( 7);
            Hx_mag(h,m,neigen) = A( 8);
            Hx_ang(h,m,neigen) = A( 9);
            Hy_mag(h,m,neigen) = A(10);
            Hy_ang(h,m,neigen) = A(11);
            Hz_mag(h,m,neigen) = A(12);
            Hz_ang(h,m,neigen) = A(13);
        end
        neigen = neigen + 1; %advance to the next mode
        
    end
    if strncmp(tline, 'LW_STEP: Conversion coefficients',length('LW_STEP: Conversion coefficients'))
        slabnr = sscanf(tline,'%s%s%s%s%s %f'); %read in the slab number line
        slabnr = slabnr(end);                   %keep only the number
        
        tline = fgetl(fid);                     %
        n = n+1;
        while ~strncmp(tline,'  rho   lat',length('  rho   lat'))
            if strncmp(tline,'A(',2)
                %read in mode numbers, conversion coefficients
                A = sscanf(tline,'A( %i, %i)= %f %f ');
                Amk{slabnr}(A(1),A(2))=complex(A(3),A(4)); %store in cell array
                
                tline = fgetl(fid);
                n = n+1;
            else
                tline = fgetl(fid);
                n = n+1;
            end
        end
    end
    if strncmp(tline, '  rho   lat    lon  azim   dip mgfld  sigma eps beta  h',length('  rho   lat    lon  azim   dip mgfld  sigma eps beta  h'))
        tline = fgetl(fid);
        n = n+1;
        A = sscanf(tline,'%f %f %f %f %f %f %f %f %f %f %f');
        nummodes = A(end);
                %advance the line until you read the beginning of the mode list
        while ~strncmp(tline,' mode  atten   v/c         rel exc 1',length(' mode  atten   v/c         rel exc 1'))
            tline = fgetl(fid);
            n = n+1;
        end
            tline = fgetl(fid);
            n = n+1;
        %until the end of the mode list, record attena and v/c
        for mm = 1:nummodes
            
            A = sscanf(tline, '%f %f %f %f %f %f %f %f %f');
            try
                atten(m,A(1)) = A(2);
                voverc(m,A(1)) = A(3);
            catch
                sprintf('Error message')
            end
            tline = fgetl(fid);
            n = n+1;
        end
    end
end
fclose(fid);

%for consistency with height gains, drop the last rho (endpoint of path)
mds     =   mds(1:end-1);
lat     =   lat(1:end-1);
lon     =   lon(1:end-1);
rho     =   rho(1:end-1);
azim    =   azim(1:end-1);
dip     =   dip(1:end-1);
bfield  =   bfield(1:end-1);
sigma   =   sigma(1:end-1);
epsr    =   epsr(1:end-1);
beta    =   beta(1:end-1);
hpr     =   hpr(1:end-1);
eigen   =   eigen(1:end-1,:);
fofr    =   fofr(1:end-1,:);
T1      =   T1(1:end-1,:);
T2      =   T2(1:end-1,:);
T3      =   T3(1:end-1,:);
T4      =   T4(1:end-1,:);
eigens(end) = [];
% eigenavg = (eigen+eigen50)./2;
% for nn=1:length(eigens)
%     eigensavg{nn} = (eigens{nn}+eigens50{nn})./2;
end






